### ISSUE TITLE
name is not defined

### ISSUE THREAD

**Issue by dashed** [sintloer/parcel-plugin-shebang#1]
For `v1.2.0`, I'm getting this error in my parcel project when I try to build (see logs below).

Repo in question: https://github.com/dashed/albertoleal

However, it works when I try to downgrade to `v1.0.3`.

This LOC seems to be the issue: https://github.com/sintloer/parcel-plugin-shebang/blob/5a3443e81b3c92ba090ee9f13bd137cafb737926/utils.js#L81

--------

```sh
$ yarn build
yarn run v1.12.3
$ parcel build source/cli.js --target=node --out-dir=bin/ --bundle-node-modules --no-source-maps
✨  Built in 2.40s.

bin/cli.js                 181.73 KB    2.27s
bin/avatar.f4ca419f.png     51.03 KB    174ms
🚨  name is not defined
    at getBundles (/path/to/albertoleal/node_modules/parcel-plugin-shebang/utils.js:81:3)
    at Bundler.bundler.on.bundle (/path/to/albertoleal/node_modules/parcel-plugin-shebang/index.js:21:21)
    at emitOne (events.js:116:13)
    at Bundler.emit (events.js:211:7)
    at Bundler.bundle (/path/to/albertoleal/node_modules/parcel-bundler/src/Bundler.js:324:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by cyntler** [comment]
@dashed, I published 1.2.2 version. The above error should no longer occur.

**Comment by dashed** [comment]
@sintloer thanks for looking into this. I've tested it out on my project (https://github.com/dashed/albertoleal), but it doesn't seem to work as expected. 

It seems that this shebang regex is not reliable: https://github.com/sintloer/parcel-plugin-shebang/blob/1410fc1cefeb35806e09784e80954f524d3a5062/utils.js#L8

since this sequence of characters, `#!`, can occur in the bundled source code.

**Comment by cyntler** [comment]
> @sintloer thanks for looking into this. I've tested it out on my project (https://github.com/dashed/albertoleal), but it doesn't seem to work as expected.
> 
> It seems that this shebang regex is not reliable:
> 
> [parcel-plugin-shebang/utils.js](https://github.com/sintloer/parcel-plugin-shebang/blob/1410fc1cefeb35806e09784e80954f524d3a5062/utils.js#L8)
> 
> Line 8 in [1410fc1](/sintloer/parcel-plugin-shebang/commit/1410fc1cefeb35806e09784e80954f524d3a5062)
> 
>  const SHEBANG_REGEX = /#!(.*) (.*)\n/; 
> since this sequence of characters, `#!`, can occur in the bundled source code.

@dashed, try with 1.2.3 version.
