### ISSUE TITLE
Update for Parcel V2

### ISSUE THREAD

**Issue by ezra-obiwale** [sintloer/parcel-plugin-shebang#15]
This doesn't work for Parcel version 2.

**Comment by cyntler** [comment]
@ezra-obiwale Yes, this plugin is created for Parcel in 1.x version. I didn't use Parcel ver. 2.x but I assume the functionality of thus plugin is working with Parcel 2 out of the box. Are you sure it is needed to fit this plugin for Parcel 2?

**Comment by ezra-obiwale** [comment]
@cyntler Yes, Parcel 2 sure needs a bespoke plugin. For one, the plugin name convention has changed. One or two other things probably changed too.

**Comment by cyntler** [comment]
Hey @ezra-obiwale. Lately I have a more free time and I wanted to make the second one plugin for Parcel 2 but before I tried to use Parcel 2 for the simple CLI app. It is working out-of-the-box to me. All I had to do was adding:

```
"targets": {
    "main": {
      "context": "node"
    }
  }
``` 

to package.json
and final bundled file has shebang line.

In this case I think I can close this issue. Do you confirm?

**Comment by ezra-obiwale** [comment]
@cyntler Thanks for the response. And sorry for MY late response.

I'll check it out and let you know if it works.

**Comment by cyntler** [comment]
> @cyntler Thanks for the response. And sorry for MY late response.
> 
> I'll check it out and let you know if it works.

@ezra-obiwale Ok, thanks!

**Comment by ezra-obiwale** [comment]
@cyntler Works well. The appropriate shebang is applied.

The resulting script doesn't work still though.
