### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by lgraubner** [sintloer/parcel-plugin-shebang#2]
This plugin does not work for me. The latest version results in #1. The version 1.1.2 (and below) results in `Unexpected character '#'`. I'm running parcel `1.11.0` and have the shebang in the entry source file.

**Comment by dashed** [comment]
@lgraubner have you tried downgrading to `v1.0.3`?

**Comment by cyntler** [comment]
> This plugin does not work for me. The latest version results in #1. The version 1.1.2 (and below) results in `Unexpected character '#'`. I'm running parcel `1.11.0` and have the shebang in the entry source file.

@lgraubner, searching for shebang in the entry source file only works since 1.2.0. In earlier versions, the plugin only worked with the configuration. You should use 1.2.x. And the error that occurs in #1 will be fixed tomorrow.

**Comment by lgraubner** [comment]
Thanks for your response. That explains a lot and I'm going to test again with the next release.

**Comment by cyntler** [comment]
@lgraubner, check version 1.2.2.

**Comment by lgraubner** [comment]
Works, thanks!
