### ISSUE TITLE
Shebang is wrong

### ISSUE THREAD

**Issue by auxves** [sintloer/parcel-plugin-shebang#3]
Expected: 
```
#!/usr/bin/env node
```

Actual
```
#! ?/,"").split(" "),u=n[0].split("/").pop(),a=n[1];return"env"===u?a:u+(a?" "+a:"")};
```

I'm using `v1.2.8`

**Comment by cyntler** [comment]
@arnohovhannisyan what was/is your `parcel-bundler` version in this case?

**Comment by auxves** [comment]
@cyntl3r At the time, it was probably `^1.12.3`. I'm not sure it still happens with the current version, but I'll test it out as soon as I can.

**Comment by auxves** [comment]
@cyntl3r I can confirm that this issue still exists with the newest version of Parcel, but only on [this project](https://github.com/arnohovhannisyan/bw-password-picker).
