### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by giveerr** [sintloer/parcel-plugin-shebang#8]
i have error when i try to watch my script

i use figlet and i imported an module ( i bundle this with the output ) call as Standard.js.
and the error is

```bash
Invalid data:$@
SOMEPATHANDLİNES
throw error;
^

Error: Error parsing data.
    at Function.me.parseFont (SOMEPATHANDLİNES/node_modules/figlet/lib/figlet.js:1070:19)
```

i think it couse from this module becouse it starts when i use this package. this package is awesome but why do this package remove blank lines 
https://github.com/cyntl3r/parcel-plugin-shebang/blob/4f260bd31773426d6461e878077c8b96a63e3a82/utils.js#L56

thank you for your interest in advance

**Comment by giveerr** [comment]
i have closed this pull request for solve this error take look at
https://www.npmjs.com/package/parcel-plugin-shebang2

**Comment by cyntler** [comment]
@giveerr I removed `removeBlankLines` function and made a new release.
